package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fitquest-backend/database"
	"fitquest-backend/graph/model"
	"fmt"
	"log"

	"go.mongodb.org/mongo-driver/bson"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, username string, password string) (*model.AuthPayload, error) {
	panic(fmt.Errorf("not implemented: Register - register"))
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, username string, password string) (*model.AuthPayload, error) {
	panic(fmt.Errorf("not implemented: Login - login"))
}

// Workouts is the resolver for the workouts field.
func (r *queryResolver) Workouts(ctx context.Context) ([]*model.Workout, error) {
	// Access the "fitquest" database and "workouts" collection from MongoDB Atlas
	collection := r.DB.Database("fitquest").Collection("workouts")

	// Find all documents
	cursor, err := collection.Find(ctx, bson.M{})
	if err != nil {
		log.Printf("Error fetching workouts from MongoDB Atlas: %v", err)
		return nil, err
	}
	defer cursor.Close(ctx)

	// Decode documents using the safe models in your database folder
	var mongoWorkouts []database.MongoWorkout
	if err = cursor.All(ctx, &mongoWorkouts); err != nil {
		log.Printf("Error decoding workouts: %v", err)
		return nil, err
	}

	var gqlWorkouts []*model.Workout
	for _, mw := range mongoWorkouts {
		gqlWorkouts = append(gqlWorkouts, mapMongoWorkoutToGQL(mw))
	}

	return gqlWorkouts, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
