package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fitness-backend/graph/model"
	"fmt"
)

// GetWorkoutTemplates is the resolver for the getWorkoutTemplates query.
func (r *queryResolver) GetWorkoutTemplates(ctx context.Context) ([]*model.WorkoutTemplate, error) {
	return r.workoutTemplates, nil
}

// GetWorkoutTemplate is the resolver for the getWorkoutTemplate field.
func (r *queryResolver) GetWorkoutTemplate(ctx context.Context, id string) (*model.WorkoutTemplate, error) {
	for _, template := range r.workoutTemplates {
		if template.ID == id {
			return template, nil
		}
	}

	return nil, fmt.Errorf("workout template %q not found", id)
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
