package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"
	"fitquest-backend/auth"
	"fitquest-backend/graph"
	"fitquest-backend/graph/mapping"
	"fitquest-backend/graph/model"
)

// Exercises is the resolver for the exercises field.
func (r *QueryResolver) Exercises(ctx context.Context, id *string) ([]*model.Exercise, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}

	mongoExercises, err := r.Resolver.Exercises.FindAll(ctx)
	if err != nil {
		return nil, err
	}

	var gqlExercises []*model.Exercise
	for _, me := range mongoExercises {
		gqlExercises = append(gqlExercises, mapping.MapMongoExerciseToGQL(me))
	}

	return gqlExercises, nil
}

// FilteredExercises is the resolver for the filteredExercises field.
func (r *QueryResolver) FilteredExercises(ctx context.Context, where model.ExerciseFilter) ([]*model.Exercise, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}

	var muscle *string
	if where.Muscle != nil {
		muscle = where.Muscle
	}

	mongoExercises, err := r.Resolver.Exercises.FindFiltered(ctx, muscle)
	if err != nil {
		return nil, err
	}

	var gqlExercises []*model.Exercise
	for _, me := range mongoExercises {
		gqlExercises = append(gqlExercises, mapping.MapMongoExerciseToGQL(me))
	}

	return gqlExercises, nil
}

func requireAuth(ctx context.Context) (*auth.UserCtx, error) {
	user := auth.ForContext(ctx)
	if user == nil {
		return nil, errors.New("authentication required")
	}
	return user, nil
}

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &QueryResolver{r} }

type QueryResolver struct{ *Resolver }
