package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"
	"fitquest-backend/auth"
	"fitquest-backend/graph"
	"fitquest-backend/graph/mapping"
	"fitquest-backend/graph/model"
)

// GetExercises is the resolver for the getExercises field.
func (r *QueryResolver) GetExercises(ctx context.Context) ([]*model.Exercise, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}

	mongoExercises, err := r.Exercises.FindAll(ctx)
	if err != nil {
		return nil, err
	}

	var gqlExercises []*model.Exercise
	for _, me := range mongoExercises {
		gqlExercises = append(gqlExercises, mapping.MapMongoExerciseToGQL(me))
	}

	return gqlExercises, nil
}

// GetFilteredExercises is the resolver for the getFilteredExercises field.
func (r *QueryResolver) GetFilteredExercises(ctx context.Context, where *model.ExerciseFilter) ([]*model.Exercise, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}

	var muscle *string
	if where != nil {
		muscle = where.Muscle
	}

	mongoExercises, err := r.Exercises.FindFiltered(ctx, muscle)
	if err != nil {
		return nil, err
	}

	var gqlExercises []*model.Exercise
	for _, me := range mongoExercises {
		gqlExercises = append(gqlExercises, mapping.MapMongoExerciseToGQL(me))
	}

	return gqlExercises, nil
}

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &QueryResolver{r} }

type QueryResolver struct{ *Resolver }

func requireAuth(ctx context.Context) (*auth.UserCtx, error) {
	user := auth.ForContext(ctx)
	if user == nil {
		return nil, errors.New("authentication required")
	}
	return user, nil
}
