package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fitquest-backend/graph"
	"fitquest-backend/graph/model"
	"fmt"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, username string, password string) (*model.AuthPayload, error) {
	panic(fmt.Errorf("not implemented: Register - register"))
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, username string, password string) (*model.AuthPayload, error) {
	panic(fmt.Errorf("not implemented: Login - login"))
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *MutationResolver) Register(ctx context.Context, username string, password string) (*model.AuthPayload, error) {
	existing, err := r.Users.FindByUsername(ctx, username)
	if err != nil {
		log.Printf("Error checking existing user: %v", err)
		return nil, err
	}
	if existing != nil {
		return nil, errors.New("username already taken")
	}

	hash, err := bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)
	if err != nil {
		log.Printf("Error hashing password: %v", err)
		return nil, err
	}

	user := database.MongoUser{
		ID:           primitive.NewObjectID(),
		Username:     username,
		PasswordHash: string(hash),
	}

	if err := r.Users.Insert(ctx, user); err != nil {
		log.Printf("Error inserting user: %v", err)
		return nil, err
	}

	token, err := jwtlib.GenerateToken(user.ID.Hex(), username)
	if err != nil {
		log.Printf("Error generating token: %v", err)
		return nil, err
	}

	return &model.AuthPayload{
		Token: token,
		User:  mapping.MapMongoUserToGQL(user),
	}, nil
}
func (r *MutationResolver) Login(ctx context.Context, username string, password string) (*model.AuthPayload, error) {
	user, err := r.Users.FindByUsername(ctx, username)
	if err != nil {
		log.Printf("Error finding user: %v", err)
		return nil, errors.New("invalid username or password")
	}
	if user == nil {
		return nil, errors.New("invalid username or password")
	}

	err = bcrypt.CompareHashAndPassword([]byte(user.PasswordHash), []byte(password))
	if err != nil {
		return nil, errors.New("invalid username or password")
	}

	token, err := jwtlib.GenerateToken(user.ID.Hex(), username)
	if err != nil {
		log.Printf("Error generating token: %v", err)
		return nil, err
	}

	return &model.AuthPayload{
		Token: token,
		User:  mapping.MapMongoUserToGQL(*user),
	}, nil
}
type MutationResolver struct{ *Resolver }
*/
