// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type User struct {
	ID               string `json:"id"`
	Username         string `json:"username"`
	Level            int32  `json:"level"`
	ExperiencePoints int32  `json:"experiencePoints"`
}

type Workout struct {
	ID              string `json:"id"`
	UserID          string `json:"userId"`
	ActivityType    string `json:"activityType"`
	DurationMinutes int32  `json:"durationMinutes"`
	XpEarned        int32  `json:"xpEarned"`
}
