// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Exercise struct {
	Name              string `json:"name"`
	EquipmentRequired string `json:"equipmentRequired"`
	PrimaryMuscle     string `json:"primaryMuscle"`
}

type Query struct {
}

type Workout struct {
	ID                  string      `json:"id"`
	Title               string      `json:"title"`
	Category            string      `json:"category"`
	Difficulty          string      `json:"difficulty"`
	Description         string      `json:"description"`
	TargetMuscleGroups  []string    `json:"targetMuscleGroups"`
	Exercises           []*Exercise `json:"exercises"`
	IsCommunityTemplate bool        `json:"isCommunityTemplate"`
}
