// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthPayload struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type Exercise struct {
	ID               string    `json:"id"`
	Name             string    `json:"name"`
	Category         *string   `json:"category,omitempty"`
	Mechanic         *string   `json:"mechanic,omitempty"`
	PrimaryMuscles   []*string `json:"primaryMuscles,omitempty"`
	SecondaryMuscles []*string `json:"secondaryMuscles,omitempty"`
}

type ExerciseFilter struct {
	Muscle *string `json:"muscle,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}
